In [ ]:
import pandas as pd
import numpy as np
import nltk
import os
import re
from nltk.corpus import movie_reviews
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
print(movie_reviews.categories()) ## Target Variable

['neg', 'pos']


In [ ]:
neg_reviews = movie_reviews.fileids('neg')
pos_reviews = movie_reviews.fileids('pos')
# pos_reviews

In [ ]:
review_list = []
for filename in neg_reviews:
    text = movie_reviews.words(filename)
    text = ' '.join(text)
    new_text = re.sub('[^A-Za-z0-9]+',' ',text)
    review_list.append(new_text)
# review_list

for filename in pos_reviews:
    text = movie_reviews.words(filename)
    text = ' '.join(text)
    new_text = re.sub('[^A-Za-z0-9]+',' ',text)
    review_list.append(new_text)
len(review_list)

2000

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
count_vector = CountVectorizer(stop_words= 'english',lowercase=True,min_df=2)

In [ ]:
x_count = count_vector.fit_transform(review_list)
x_count.shape


(2000, 23757)

In [ ]:
col_names = count_vector.get_feature_names()

In [ ]:
x_df = pd.DataFrame(x_count.toarray(),columns=col_names)
x_df

00  000  007  05  10  100  1000  100m  101  102  ...  zoom  zooming  \
0      0    0    0   0  10    0     0     0    0    0  ...     0        0   
1      0    0    0   0   0    0     0     0    0    0  ...     0        0   
2      0    0    0   0   0    0     0     0    0    0  ...     0        0   
3      0    0    0   0   0    0     0     0    0    0  ...     0        0   
4      0    0    0   0   0    0     0     0    0    0  ...     0        0   
...   ..  ...  ...  ..  ..  ...   ...   ...  ...  ...  ...   ...      ...   
1995   0    0    0   0   1    0     0     0    0    0  ...     0        0   
1996   0    0    0   0   0    0     0     0    0    0  ...     0        0   
1997   0    0    0   0   1    0     0     0    0    0  ...     0        0   
1998   0    0    0   0   1    0     0     0    0    0  ...     0        0   
1999   0    0    0   0   0    0     0     0    0    0  ...     0        0   

      zooms  zoot  zorg  zorro  zucker  zuko  zwick  zwigoff  
0         0     0     0      0       0     0      0        0  
1         0     0     0      0       0     0      0        0  
2         0     0     0      0       0     0      0        0  
3         0     0     0      0       0     0      0        0  
4         0     0     0      0       0     0      0        0  
...     ...   ...   ...    ...     ...   ...    ...      ...  
1995      0     0     0      0       0     0      0        0  
1996      0     0     0      0       0     0      0        0  
1997      0     0     0      0       0     0      1        0  
1998      0     0     0      0       0     0      0        0  
1999      0     0     0      0       0     0      0        0  

[2000 rows x 23757 columns]

In [ ]:
x_df.tail()

00  000  007  05  10  100  1000  100m  101  102  ...  zoom  zooming  \
1995   0    0    0   0   1    0     0     0    0    0  ...     0        0   
1996   0    0    0   0   0    0     0     0    0    0  ...     0        0   
1997   0    0    0   0   1    0     0     0    0    0  ...     0        0   
1998   0    0    0   0   1    0     0     0    0    0  ...     0        0   
1999   0    0    0   0   0    0     0     0    0    0  ...     0        0   

      zooms  zoot  zorg  zorro  zucker  zuko  zwick  zwigoff  
1995      0     0     0      0       0     0      0        0  
1996      0     0     0      0       0     0      0        0  
1997      0     0     0      0       0     0      1        0  
1998      0     0     0      0       0     0      0        0  
1999      0     0     0      0       0     0      0        0  

[5 rows x 23757 columns]

In [ ]:
neg_target = np.zeros((1000),dtype=np.int)
pos_target = np.ones((1000),dtype=np.int)
y_list = list(neg_target) + list(pos_target)
len(y_list)
y = pd.Series(y_list)


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x_df,y,test_size = 0.2,random_state = 1)

## MOdel Selection

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
gnb = GaussianNB()
mnb = MultinomialNB()

In [ ]:
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = gnb.predict(x_test)

In [ ]:
y_pred[15:20],y_test[15:20]

(array([0, 1, 1, 0, 0]), 1813    1
 654     0
 1264    1
 858     0
 1482    1
 dtype: int64)

In [ ]:
accuracy_score(y_test,y_pred)

0.6575

In [ ]:
mnb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred_mnb = mnb.predict(x_test)

In [ ]:
y_pred_mnb[15:20],y_test[15:20]

(array([1, 0, 1, 0, 1]), 1813    1
 654     0
 1264    1
 858     0
 1482    1
 dtype: int64)

In [ ]:
accuracy_score(y_test,y_pred_mnb)

0.7675

In [ ]:
confusion_matrix(y_test,y_pred_mnb)

array([[159,  36],
       [ 57, 148]])